(* generated by Ott 0.21.2 from: handlers.ott *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import Handlers.
Require Import HandlersEx.
Open Scope string_scope.


Example runStateComp : reds (outer (runState comp)) expectedResult.
eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply handleOp.
    tauto.
    eapply hFor with (i:=1). simpl. reflexivity. constructor.

simpl. eapply r_step.
  eapply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply frame with (CC5:=CC_App _).
  apply betaU.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply handleOp.
    tauto.
    eapply hFor with (i:=2). simpl. reflexivity. constructor.

simpl. eapply r_step.
  apply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply frame with (CC5:=CC_App _).
  apply betaU.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply handleOp.
    tauto.
    eapply hFor with (i:=1). simpl. reflexivity. constructor.

simpl. eapply r_step.
  apply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply frame with (CC5:=CC_App _).
  apply betaU.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply handleOp.
    tauto.
    eapply hFor with (i:=2). simpl. reflexivity. constructor.

simpl. eapply r_step.
  apply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply frame with (CC5:=CC_App _).
  apply betaU.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply handleOp.
    tauto.
    eapply hFor with (i:=1). simpl. reflexivity. constructor.

simpl. eapply r_step.
  apply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply frame with (CC5:=CC_App _).
  apply betaU.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply betaApp.

simpl. eapply r_step.
  eapply frame with (CC5:=CC_App _).
  eapply handleF.
    apply hReturns.

simpl. eapply r_step.
  apply betaApp.

simpl. apply r_zero.
Qed.

